<!-- Refiral Campaign Code Begin -->
<script type="text/javascript">
if ( (typeof jQuery === 'undefined') && !window.jQuery )
{
	document.write(unescape("%3Cscript type='text/javascript' src='http://code.jquery.com/jquery-latest.min.js'%3E%3C/script%3E"));
}
else
{
	if((typeof jQuery === 'undefined') && window.jQuery) 
	{
		jQuery = window.jQuery;
	}
	else if((typeof jQuery !== 'undefined') && !window.jQuery) 
	{
		window.jQuery = jQuery;
	}
}
</script>
<script>var $j = jQuery.noConflict();</script>
<?php
$_helper = Mage::helper('campaign');
if($_helper->isActive())
	echo $_helper->getScript();
?>
<!-- Refiral Campaign Code End -->